name: Update EPW RSS Automatically
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml
          
      - name: Generate RSS feed
        run: |
          cat > generate_rss.py << 'EOF'
          import requests
          from bs4 import BeautifulSoup
          import datetime
          
          # Simple RSS generator
          def generate_rss():
              url = "https://www.epw.in/editorials"
              
              try:
                  response = requests.get(url, timeout=10)
                  soup = BeautifulSoup(response.content, 'lxml')
                  
                  rss_content = ['<?xml version="1.0"?>']
                  rss_content.append('<rss version="2.0">')
                  rss_content.append('<channel>')
                  rss_content.append('<title>EPW Editorials</title>')
                  rss_content.append('<link>https://www.epw.in/editorials</link>')
                  rss_content.append('<description>EPW Editorials Auto Feed</description>')
                  
                  # Simple article extraction
                  count = 0
                  for link in soup.find_all('a', href=True):
                      href = link['href']
                      text = link.get_text().strip()
                      
                      if ('engage' in href or 'journal' in href) and len(text) > 30:
                          if not href.startswith('http'):
                              href = 'https://www.epw.in' + href
                          
                          rss_content.append('<item>')
                          rss_content.append(f'<title>{text}</title>')
                          rss_content.append(f'<link>{href}</link>')
                          rss_content.append(f'<pubDate>{datetime.datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT")}</pubDate>')
                          rss_content.append('</item>')
                          
                          count += 1
                          if count >= 10:
                              break
                  
                  rss_content.append('</channel>')
                  rss_content.append('</rss>')
                  
                  return '\n'.join(rss_content)
                  
              except Exception as e:
                  # Fallback RSS
                  return f'''<?xml version="1.0"?>
<rss version="2.0">
<channel>
<title>EPW Editorials</title>
<link>https://www.epw.in/editorials</link>
<description>EPW Editorials - Error: {e}</description>
<item>
<title>Check EPW Website for New Editorials</title>
<link>https://www.epw.in/editorials</link>
<pubDate>{datetime.datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT")}</pubDate>
</item>
</channel>
</rss>'''
          
          # Write RSS file
          rss_output = generate_rss()
          with open('epw-feed.xml', 'w') as f:
              f.write(rss_output)
          
          print("RSS feed generated successfully")
          EOF
          
          python generate_rss.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epw-feed.xml
          git diff --staged --quiet || git commit -m "Auto-update EPW RSS"
          git push
