name: Update EPW RSS Automatically
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:        # Manual trigger

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgenerator
        
      - name: Run RSS generator
        run: |
          cat > generate_rss.py << 'EOF'
          import requests
          from bs4 import BeautifulSoup
          from feedgen.feed import FeedGenerator
          import datetime
          
          # Scrape EPW editorials
          url = "https://www.epw.in/editorials"
          response = requests.get(url)
          soup = BeautifulSoup(response.content, 'html.parser')
          
          # Create RSS feed
          fg = FeedGenerator()
          fg.title('EPW Editorials')
          fg.link(href=url, rel='alternate')
          fg.description('Automated EPW Editorials Feed')
          
          # Find articles - this will need tuning for EPW's structure
          articles = []
          for link in soup.find_all('a', href=True):
              href = link['href']
              text = link.get_text().strip()
              if ('/engage/' in href or '/journal/' in href) and len(text) > 30:
                  if href.startswith('/'):
                      href = 'https://www.epw.in' + href
                  articles.append({'title': text, 'link': href})
          
          # Add items to feed
          for article in articles[:15]:  # Limit to 15 articles
              fe = fg.add_entry()
              fe.title(article['title'])
              fe.link(href=article['link'])
              fe.pubDate(datetime.datetime.utcnow())
          
          # Generate RSS file
          fg.rss_file('epw-feed.xml')
          EOF
          
          python generate_rss.py
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epw-feed.xml
          git diff --staged --quiet || git commit -m "Auto-update EPW RSS"
          git push
